version: "2"
services:
  db:
    image: mongo
    expose:
      - 27017
  web:
    build:
      context: .
      dockerfile: Dockerfile.build
    environment:
      PORT: 8080
      MONGODB_URL: db/test
    command: [./url-shortener]
    volumes:
      - ./public:/go/src/app/public
    ports:
      - '8080:8080'
    links:
      - db
